.TH phoronix-test-suite 1  "www.phoronix-test-suite.com" "Version 1.0" "BASIC COMMANDS"
.SH NAME
phoronix-test-suite \- The Phoronix Test Suite is an extensible open-source (GNU GPLv3) platform for performing Linux-based testing and performance evaluation.
.SH SYNOPSIS
.B phoronix-test-suite [options]
.SH DESCRIPTION
The Phoronix Test Suite is the most comprehensive testing and benchmarking platform available for Linux and is designed to carry out qualitative and quantitative benchmarks in a clean, reproducible, and easy-to-use manner. This software is based upon the internal tools and extensive Linux benchmarking work done by Phoronix since 2004, with input from tier-one computer hardware vendors. This software is open-source and licensed under the GNU GPLv3 and consists of a lightweight core (pts-core) with each benchmark consisting of an XML-based profile with related utility scripts. The process from the benchmark installation, to the actual benchmarking, to the parsing of important hardware and software components is heavily automated and completely repeatable, asking users only for confirmation of actions.
.PP
The Phoronix Test Suite can be used for simply comparing your computer's performance with your friends and co-workers or can also be used at your company for internal quality assurance purposes under Linux. Results from the Phoronix Test Suite are displayed in a results viewer with optional support for uploading them to PTS Global. PTS Global allows you to browse all uploaded results, search these results, and comparing other results against your own system.
.SH OPTIONS
.TP
.B install <To Install>
This option will install the selected test(s) inside the testing environment directory (defaults to ~/.phoronix-test-suite/installed-tests). The install process from downloading of the test files to the installation is fully automated. The install option needs to be supplied with the test name or suite as an argument. Optionally, a PTS Global ID or the name of a saved results file can be supplied as well and the test(s) to install will automatically be extracted from that information. If the test is already installed and was ran by the latest version of the installation process, no action will be taken.
.TP
.B benchmark <To Run>
This option will install the selected test(s) (if needed) and will proceed to run the test(s). This option is equivalent to running phoronix-test-suite with the install option followed by the run option. The name of the test or suite must be supplied or the PTS Global ID or saved local file name.
.TP
.B batch-benchmark <To Run>
This option and its arguments are equivalent to the benchmark option, but the process will be ran in the Phoronix Test Suite batch mode.
.TP
.B list-tests
This option will list all available tests. The name, title, status, and license are displayed for each test.
.TP
.B list-suites
This option will list all available test suites. The name, title, and type are displayed for each suite.
.TP
.B merge-results <To Merge> <To Merge> <To Save As>
This option will manually merge two sets of test results generated by the Phoronix Test Suite. The merged results will then be saved to a new file if the targeted save name is specified as the third argument otherwise the results will be re-saved to first file. For the first two arguments, the name of the test or suite must be supplied or the PTS Global ID or saved local file name.
.B info <To Show>
This option will show details about the test or suite that's supplied as the first argument to this option. When supplying the name of a test, the version, maintainer, type, download size, license information, and suites using this test are displayed. When supplying the name of a suite, the version, maintainer, type, and tests that make up the suite are displayed.
.TP
.B login
This option allows you to log-in to your PTS Global account and will store this information automatically. A new PTS Global account can be created (for free) at http://global.phoronix-test-suite.com/.
.SH ALL OPTIONS
To view all options and more information, view the included documentation or view the online documentation at:
.PP
.B http://www.phoronix-test-suite.com/documentation/1.0/index.html
.SH EXAMPLES
.TP
.B $ phoronix-test-suite benchmark universe
This command will install (if needed) and then proceed to run all tests within the universe suite.
.TP
.B $ phoronix-test-suite install openssl
This command will install (if needed) the OpenSSL test.
.TP
.B $ phoronix-test-suite benchmark build-linux-kernel
This command will install (if needed) and then proceed to run the build-linux-kernel test.
.TP
.B $ MONITOR=all phoronix-test-suite benchmark universe
This command will install (if needed) and then proceed to run all tests within the universe suite, while recording/monitoring available system sensors. The sensor results are then shown at the end of the test.
.SH SUPPORT
Limited free support for the Phoronix Test Suite is available through the Phoronix Forums (see http://www.phoronix.com/forums/) or the Phoronix Test Suite Mailing List. Support and other services can also be made available to enterprise customers on an individual basis by contacting Michael Larabel or Phoronix Media at http://www.phoronix.com/.
.SH AUTHORS
Copyright 2008 by Phoronix Media
.TP
.B Lead Developers:
Michael Larabel (Michael [at] phoronix.com)
.br
Wuppermann
.br
Andrew Schofield
.SH SEE ALSO
.TP
.B Websites:
.br
http://www.phoronix.com/
.br
http://www.phoronix.com/forums/
.br
http://www.phoronix-test-suite.com/
.br
http://global.phoronix-test-suite.com/

