#!/bin/sh

# Example script for Phoromatic Kernel Tracker
# http://kernel-tracker.phoromatic.com/
# Toss into /etc/ and is called by update-kernel-from-ubuntu-daily-ppa script on cron job when appropriate

mkdir /tmp/kernel-ppa
cd /tmp/kernel-ppa

wget -r --no-parent -nd http://kernel.ubuntu.com/~kernel-ppa/mainline/daily/current/
sleep 1
dpkg -i --force-confnew --force-overwrite linux-image-*_amd64.deb
sleep 10
update-grub
cd /
rm -rf /tmp/kernel-ppa
reboot
