#!/bin/sh

# Example script for Phoromatic Kernel Tracker
# http://kernel-tracker.phoromatic.com/
# Toss into /etc/cron.hourly/

hour=`date +%k`
# hour=7
if [ $hour -ne 7 ] ; then
        exit
fi

/etc/phoromatic-tracker-update-kernel > /tmp/update-kernel-log 2>&1

